pom.xml: force joda-time to version 2.8.1
Which is required when running on JDK 1.8u60 and newer.

Tests are failing with:
> com.amazonaws.services.s3.model.AmazonS3Exception: AWS authentication
> requires a valid Date or x-amz-date header

Reference: https://github.com/aws/aws-sdk-java/commit/30b3d16